// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fbstrans/order/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: OrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/createOrderRequest",
				Handler: CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/cancelOrderRequest",
				Handler: CreateOrderCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/quickOrder",
				Handler: QuickOrderHandler(serverCtx),
			},
		},
	)
}
