// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type CreateOrderRequest struct {
	UserId  int64 `json:"user_id"`
	GoodsId int64 `json:"goods_id"`
	Num     int64 `json:"num"`
}

type CreateOrderResponse struct {
	OrderId int64 `json:"order_id"`
}
